### ISSUE TITLE
Don't hard-code the database name

### ISSUE THREAD

**Issue by NatoBoram** [ide-stories/vscode-stories-api#10]
From the `README.md` : 

> 2. Create a database called stories

I think it would be best to avoid hard-coding database names and use the `.env` file instead.

**Comment by YerinAlexey** [comment]
Database name is loaded from [ormconfig.json](https://github.com/benawad/vscode-stories-api/blob/51f7c3600fba31e7cf05ab79252a1b3a7224240a/ormconfig.json#L5)
