### ISSUE TITLE
Add NSFW filter to usernames.

### ISSUE THREAD

**Issue by stemount** [ide-stories/vscode-stories-api#7]
Relates to https://github.com/benawad/vscode-stories/issues/22 however this issue is in the wrong API cc @benawad @hariacidreign @yashmunjal

**Acceptance Criteria**
- Profanity filter on usernames has some tests
-- The tests could be quite a fun test run "When some pillock tries to set username as Sh1tbagDeveloper"
- Find a library off the shelf ideally that has an epic filter over a regex ideally...

**Implementation notes**
- There are ways to implement unsafe regex so this must be considered for security scrutiny when the PR is open.
- Might be worth "upping" the rate limiting (if there is any) on setting a username to prevent somebody trying a dictionary/wordlist of profanity.

**Comment by stemount** [comment]
@HariAcidReign @YashMunjal
There is also note that this is sort of fixed by the idea of social login because it would mean it would be an arduous process to just create GitHub/MS accounts with daft usernames. cc @benawad for priority/appetite to do social login

**Comment by benawad** [comment]
yeah I switched it over to github login, so I don't think we need to worry about this anymore
